[window]
decorations = "Buttonless"
opacity = 1.93
blur = true

# [font]
# size = 14.0
# normal.family = "FiraCode Nerd Font"
# bold.family = "FiraCode Nerd Font"
# italic.family = "FiraCode Nerd Font"
# bold_italic.family = "FiraCode Nerd Font"

# [font]
# size = 14.0
# normal.family = "BigBlueTerm437 Nerd Font"
# bold.family = "BigBlueTerm437 Nerd Font"
# italic.family = "BigBlueTerm437 Nerd Font"
# bold_italic.family = "BigBlueTerm437 Nerd Font"

[font]
size = 14.0
normal.family = "BigBlueTermPlus Nerd Font"
bold.family = "BigBlueTermPlus Nerd Font"
italic.family = "BigBlueTermPlus Nerd Font"
bold_italic.family = "BigBlueTermPlus Nerd Font"

#GITHUB THEME

# Default colors
[colors.primary]
background = '#0d1117'
foreground = '#b3b1ad'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'
